# Generated by Django 4.1.7 on 2023-06-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sound_File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=30)),
                ("file_name", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Sound_Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=30)),
                ("value", models.FloatField()),
                ("created_at", models.DateTimeField()),
            ],
        ),
    ]
